### ISSUE TITLE
Two scrollbars not ideal

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison-editor#29]
Right now the Etherpad iframe scrolls, and the main page scrolls to get to the bottom of the iframe.  Not sure what the best solution is at the moment.

**Comment by cmbirk** [comment]
We need to pass something up to the parent iframe telling it what to resize the iframe to..

**Comment by krusynth** [comment]
It might be easiest to just resize the iframe to match the contents, so it never scrolls.

http://stackoverflow.com/questions/9975810/make-iframe-automatically-adjust-height-according-to-the-contents-without-using

**Comment by krusynth** [comment]
Particularly of note in that thread: https://github.com/davidjbradshaw/iframe-resizer

**Comment by cmbirk** [comment]
That looks promising
