### ISSUE TITLE
Unable to load editor on some documents

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison-editor#30]
I'm seeing this specifically on one of the template documents.  There are a few errors in console that may be relevant
<img width="1440" alt="screen shot 2015-11-04 at 12 03 17 pm" src="https://cloud.githubusercontent.com/assets/764851/10947159/24c125c6-82ec-11e5-8397-eed180d55c84.png">

**Comment by krusynth** [comment]
This is all from etherpad.  I've never seen this at all, which document is it occurring on?

**Comment by cmbirk** [comment]
This is on 116, and I'm still getting The `setDocAText` error.  @johnmclear any ideas here?

**Comment by JohnMcLear** [comment]
looks like somehow the pad aText went corrupt :|  is this on a specific pad and can you replicate?

**Comment by cmbirk** [comment]
This was fixed by changing from latin-1 to the correct utf8 settings using:

```
ALTER DATABASE `etherpad-lite` CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

USE `etherpad-lite`;

ALTER TABLE `store` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
```
