### ISSUE TITLE
Template document replicated in documents list

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison-editor#31]
All of the templates in the included screenshot are the same document ( and link to the same page )
<img width="1339" alt="screen shot 2015-11-04 at 11 55 12 am" src="https://cloud.githubusercontent.com/assets/764851/10947186/48175ab8-82ec-11e5-9801-e82d61ee6cb0.png">

**Comment by krusynth** [comment]
Fixed in ab16c8ff4f566558bd5b1425d890ab0535859f0e
