### ISSUE TITLE
Update config/example.js

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison-editor#42]
We should set the madison creds once here and pull them in where needed.  We should also include the rest of the information our instance has in the example, such as including the mysql port in the `MySQLSessionStore` call.

**Comment by krusynth** [comment]
:+1:

**Comment by krusynth** [comment]
This actually looks like it was pulled from an out of date version, you've removed the cookie settings.  Make sure you're doing a pull --rebase from upstream before sending the PR.

**Comment by cmbirk** [comment]
Yeah, I updated it based on what I found on our server.  I can add those back in.  I was assuming the version on the server was most accurate at the moment.
