### ISSUE TITLE
Hide aesthetic controls

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison-editor#43]
@johnmclear is there a plugin or easy way to hide things like bold, italic, indent, etc?

**Comment by krusynth** [comment]
Didn't we decide that we need to keep these?

**Comment by cmbirk** [comment]
No, we're going to be applying separate styling on export anyway, so these don't make sense.  They're just a distraction

**Comment by krusynth** [comment]
I thought we discovered that lawyers are directly going to need to be able to do this for some legislation types.

**Comment by cmbirk** [comment]
Some will _think_ they need them, but the idea is to move away from this.  We aren't going to pull them right away, but it would be useful for a side-by-side demo ( different instances ) to explain the difference when the time comes.  We will eventually be dropping them.
