### ISSUE TITLE
Etherpad not loading on some comps

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison-editor#51]
I'm in the clerk's office, and I can load `editor.mymadison.io` and correctly, but trying other computers in the office, I'm getting a "server refused the connection" at "editor.mymadison.io:9001" error.  It's been tried in IE, Chrome, and Firefox.

**Comment by cmbirk** [comment]
The Madison Editor page is loading, but etherpad is not.

**Comment by JohnMcLear** [comment]
Any errors in console? Which browsers?
----- Reply message -----

**Comment by cmbirk** [comment]
I think I may have found the issue.

I'm seeing this in `/var/log/auth.log`:

```
reverse mapping checking getaddrinfo for 167-165-238-2.ip.msa1.illinois.net [167.165.238.2] failed - POSSIBLE BREAK-IN ATTEMPT!
```

although users here have been able to log in previously...

**Comment by cmbirk** [comment]
... and the users who have been able to load it previously now cannot as well.

**Comment by cmbirk** [comment]
I'm not seeing anything in the console other than a connection refused error

**Comment by krusynth** [comment]
Lessons learned:
- I need to setup that proxy (#46) or sessions are broken
- They've got port 9001 blocked at the office there.
